--- a/Makefile	2017-04-28 19:36:33.000000000 +0200
+++ b/Makefile	2017-04-29 16:58:11.164514474 +0200
@@ -1,5 +1,4 @@
 PACKAGE = sogo-connector
-GIT_REV = $(shell git rev-parse --verify HEAD | cut -c1-10)
 
 ifeq ($(shell uname),Darwin)
 VERSION = $(shell grep em:version install.rdf | sed -E 's@(em:version=|"| )@@g')
@@ -7,7 +6,7 @@
 VERSION = $(shell grep em:version install.rdf | sed -e 's@\(em:version=\|\"\|\ \)@@g')
 endif
 
-XPI_ARCHIVE = $(PACKAGE)-$(VERSION)-$(GIT_REV).xpi
+XPI_ARCHIVE = $(PACKAGE)-$(VERSION).xpi
 
 SHELL = /bin/bash
 ZIP = /usr/bin/zip
